// --- MAPPING-CODES.JS ----------------------------------------------------------------------------
/**
 * Holds the mapping system logic
 * - ISO (cca2) => FIPS + file path
 * - ISO (cca3) => Country name
 */


// =================================================================================================
// - ISO (CCA2) TO FIPS -
// =================================================================================================

// Mapping system between RESTCountries API and FactBook (The World FactBook - CIA)
// to be able to retrieve information from FactBook with data from RESTCountries API
// even though they are not using the same naming and organization system
// - RESTCountry API uses ISO code 2 whereas FactBook uses FIPS
// - RESTCountries API uses the UN demographic region naming whereas FactBook uses its own

const isoToFips = {
  "mapping_type": "ISO-3166-1-alpha-2 to GEC (FIPS)",
  "description": "Mapping of ISO 3166-1 alpha-2 to US Government GEC codes",
  "data": {
    "AF": "af",
    "AX": "ax",
    "AL": "al",
    "DZ": "dj",
    "AS": "aq",
    "AD": "an",
    "AO": "ao",
    "AI": "av",
    "AQ": "ay",
    "AG": "ac",
    "AR": "ar",
    "AM": "am",
    "AW": "aa",
    "AU": "as",
    "AT": "au",
    "AZ": "aj",
    "BS": "bf",
    "BH": "ba",
    "BD": "bg",
    "BB": "bb",
    "BY": "bo",
    "BE": "be",
    "BZ": "bh",
    "BJ": "bn",
    "BM": "bd",
    "BT": "bt",
    "BO": "bl",
    "BA": "bk",
    "BW": "bc",
    "BV": "bv",
    "BR": "br",
    "IO": "io",
    "BN": "bx",
    "BG": "bu",
    "BF": "uv",
    "BI": "by",
    "KH": "cb",
    "CM": "cm",
    "CA": "ca",
    "CV": "cv",
    "KY": "cj",
    "CF": "ct",
    "TD": "cd",
    "CL": "ci",
    "CN": "ch",
    "CX": "kt",
    "CC": "ck",
    "CO": "co",
    "KM": "cn",
    "CG": "cf",
    "CD": "cg",
    "CK": "cw",
    "CR": "cs",
    "CI": "iv",
    "HR": "hr",
    "CU": "cu",
    "CY": "cy",
    "CZ": "ez",
    "DK": "da",
    "DJ": "dj",
    "DM": "do",
    "DO": "dr",
    "EC": "ec",
    "EG": "eg",
    "SV": "es",
    "GQ": "ek",
    "ER": "er",
    "EE": "en",
    "ET": "et",
    "FK": "fk",
    "FO": "fo",
    "FJ": "fj",
    "FI": "fi",
    "FR": "fr",
    "GF": "fg",
    "PF": "fp",
    "TF": "fs",
    "GA": "gb",
    "GM": "ga",
    "GE": "gg",
    "DE": "gm",
    "GH": "gh",
    "GI": "gi",
    "GR": "gr",
    "GL": "gl",
    "GD": "gj",
    "GP": "gp",
    "GU": "gq",
    "GT": "gt",
    "GG": "gk",
    "GN": "gv",
    "GW": "pu",
    "GY": "gy",
    "HT": "ha",
    "HM": "hm",
    "VA": "vt",
    "HN": "ho",
    "HK": "hk",
    "HU": "hu",
    "IS": "ic",
    "IN": "in",
    "ID": "id",
    "IR": "ir",
    "IQ": "iz",
    "IE": "ei",
    "IM": "im",
    "IL": "is",
    "IT": "it",
    "JM": "jm",
    "JP": "ja",
    "JE": "je",
    "JO": "jo",
    "KZ": "kz",
    "KE": "ke",
    "KI": "kr",
    "KP": "kn",
    "KR": "ks",
    "KW": "ku",
    "KG": "kg",
    "LA": "la",
    "LV": "lg",
    "LB": "le",
    "LS": "lt",
    "LR": "li",
    "LY": "ly",
    "LI": "ls",
    "LT": "lh",
    "LU": "lu",
    "MO": "mc",
    "MK": "mk",
    "MG": "ma",
    "MW": "mi",
    "MY": "my",
    "MV": "mv",
    "ML": "ml",
    "MT": "mt",
    "MH": "rm",
    "MQ": "mb",
    "MR": "mr",
    "MU": "mp",
    "YT": "mf",
    "MX": "mx",
    "FM": "fm",
    "MD": "md",
    "MC": "mn",
    "MN": "mg",
    "ME": "mj",
    "MS": "mh",
    "MA": "mo",
    "MZ": "mz",
    "MM": "bm",
    "NA": "wa",
    "NR": "nr",
    "NP": "np",
    "NL": "nl",
    "NC": "nc",
    "NZ": "nz",
    "NI": "nu",
    "NE": "ng",
    "NG": "ni",
    "NU": "ne",
    "NF": "nf",
    "MP": "cq",
    "NO": "no",
    "OM": "mu",
    "PK": "pk",
    "PW": "ps",
    "PS": "gz",
    "PA": "pm",
    "PG": "pp",
    "PY": "pa",
    "PE": "pe",
    "PH": "rp",
    "PN": "pc",
    "PL": "pl",
    "PT": "po",
    "PR": "rq",
    "QA": "qa",
    "RE": "re",
    "RO": "ro",
    "RU": "rs",
    "RW": "rw",
    "BL": "rn",
    "SH": "sh",
    "KN": "sc",
    "LC": "st",
    "MF": "rn",
    "PM": "sb",
    "VC": "vc",
    "WS": "ws",
    "SM": "sm",
    "ST": "tp",
    "SA": "sa",
    "SN": "sg",
    "RS": "ri",
    "SC": "se",
    "SL": "sl",
    "SG": "sn",
    "SK": "lo",
    "SI": "si",
    "SB": "bp",
    "SO": "so",
    "ZA": "sf",
    "GS": "sx",
    "SS": "od",
    "ES": "sp",
    "LK": "ce",
    "SD": "su",
    "SR": "ns",
    "SJ": "sv",
    "SZ": "wz",
    "SE": "sw",
    "CH": "sz",
    "SY": "sy",
    "TW": "tw",
    "TJ": "ti",
    "TZ": "tz",
    "TH": "th",
    "TL": "tt",
    "TG": "to",
    "TK": "tl",
    "TO": "tn",
    "TT": "td",
    "TN": "ts",
    "TR": "tu",
    "TM": "tx",
    "TC": "tk",
    "TV": "tv",
    "UG": "ug",
    "UA": "up",
    "AE": "ae",
    "GB": "uk",
    "US": "us",
    "UM": "uq",
    "UY": "uy",
    "UZ": "uz",
    "VU": "nh",
    "VE": "ve",
    "VN": "vm",
    "VG": "vi",
    "VI": "vq",
    "WF": "wf",
    "EH": "wi",
    "YE": "ym",
    "ZM": "za",
    "ZW": "zi"
  }
}

const southAsia = ['af', 'bg', 'bt', 'ce', 'in', 'io', 'mv', 'np', 'pk']

function getFactBookFilePath(country) {
  const region = country.region
  const subregion = country.subregion
  const countryCodeIso2 = country.codes.alpha_2

  const file = convertToFIPS(countryCodeIso2)
  const folder = regionMappingToFactBook(region, subregion, file)

  return `${folder}/${file}.json`
}

function regionMappingToFactBook(region, subregion, fips) {
  switch(region) {
    case 'Africa': return 'africa'
    case 'Europe': return fips === 'rs' ? 'central-asia' : 'europe'
    case 'Antarctic': return 'antartica'
    case 'Oceania': return 'australia-oceania'
    case 'Americas':
      if (subregion.includes('North')) return 'north-america'
      if (subregion.includes('South')) return 'south-america'
      return 'central-america-n-caribbean'
    case 'Asia':
      if (subregion.includes('Central')) return 'central-asia'
      if (subregion.includes('Western')) return 'middle-east'
      if (subregion.includes('Southern')) {
        return southAsia.includes(fips) ? 'south-asia' : 'middle-east'
      }
      return 'east-n-southeast-asia'
  }
}

function convertToFIPS (isoCode2) {
    return isoToFips.data[isoCode2]
}


// =================================================================================================
// - ISO (CCA3) TO COUNTRY NAME -
// =================================================================================================

const countryCodesToNames = {
    "AFG": "Afghanistan",
    "ALB": "Albania",
    "DZA": "Algeria",
    "AND": "Andorra",
    "AGO": "Angola",
    "ATG": "Antigua and Barbuda",
    "ARG": "Argentina",
    "ARM": "Armenia",
    "AUS": "Australia",
    "AUT": "Austria",
    "AZE": "Azerbaijan",
    "BHS": "Bahamas",
    "BHR": "Bahrain",
    "BGD": "Bangladesh",
    "BRB": "Barbados",
    "BLR": "Belarus",
    "BEL": "Belgium",
    "BLZ": "Belize",
    "BEN": "Benin",
    "BTN": "Bhutan",
    "BOL": "Bolivia",
    "BIH": "Bosnia and Herzegovina",
    "BWA": "Botswana",
    "BRA": "Brazil",
    "BRN": "Brunei",
    "BGR": "Bulgaria",
    "BFA": "Burkina Faso",
    "BDI": "Burundi",
    "CPV": "Cabo Verde",
    "KHM": "Cambodia",
    "CMR": "Cameroon",
    "CAN": "Canada",
    "CAF": "Central African Republic",
    "TCD": "Chad",
    "CHL": "Chile",
    "CHN": "China",
    "COL": "Colombia",
    "COM": "Comoros",
    "COG": "Congo",
    "COD": "DR Congo",
    "CRI": "Costa Rica",
    "HRV": "Croatia",
    "CUB": "Cuba",
    "CYP": "Cyprus",
    "CZE": "Czechia",
    "DNK": "Denmark",
    "DJI": "Djibouti",
    "DMA": "Dominica",
    "DOM": "Dominican Republic",
    "ECU": "Ecuador",
    "EGY": "Egypt",
    "SLV": "El Salvador",
    "GNQ": "Equatorial Guinea",
    "ERI": "Eritrea",
    "EST": "Estonia",
    "SWZ": "Eswatini",
    "ETH": "Ethiopia",
    "FJI": "Fiji",
    "FIN": "Finland",
    "FRA": "France",
    "GAB": "Gabon",
    "GMB": "Gambia",
    "GEO": "Georgia",
    "DEU": "Germany",
    "GHA": "Ghana",
    "GRC": "Greece",
    "GRD": "Grenada",
    "GTM": "Guatemala",
    "GIN": "Guinea",
    "GNB": "Guinea-Bissau",
    "GUY": "Guyana",
    "HTI": "Haiti",
    "HND": "Honduras",
    "HUN": "Hungary",
    "ISL": "Iceland",
    "IND": "India",
    "IDN": "Indonesia",
    "IRN": "Iran",
    "IRQ": "Iraq",
    "IRL": "Ireland",
    "ISR": "Israel",
    "ITA": "Italy",
    "JAM": "Jamaica",
    "JPN": "Japan",
    "JOR": "Jordan",
    "KAZ": "Kazakhstan",
    "KEN": "Kenya",
    "KIR": "Kiribati",
    "KWT": "Kuwait",
    "KGZ": "Kyrgyzstan",
    "LAO": "Laos",
    "LVA": "Latvia",
    "LBN": "Lebanon",
    "LSO": "Lesotho",
    "LBR": "Liberia",
    "LBY": "Libya",
    "LIE": "Liechtenstein",
    "LTU": "Lithuania",
    "LUX": "Luxembourg",
    "MDG": "Madagascar",
    "MWI": "Malawi",
    "MYS": "Malaysia",
    "MDV": "Maldives",
    "MLI": "Mali",
    "MLT": "Malta",
    "MHL": "Marshall Islands",
    "MRT": "Mauritania",
    "MUS": "Mauritius",
    "MEX": "Mexico",
    "FSM": "Micronesia",
    "MDA": "Moldova",
    "MCO": "Monaco",
    "MNG": "Mongolia",
    "MNE": "Montenegro",
    "MAR": "Morocco",
    "MOZ": "Mozambique",
    "MMR": "Myanmar",
    "NAM": "Namibia",
    "NRU": "Nauru",
    "NPL": "Nepal",
    "NLD": "Netherlands",
    "NZL": "New Zealand",
    "NIC": "Nicaragua",
    "NER": "Niger",
    "NGA": "Nigeria",
    "PRK": "North Korea",
    "MKD": "North Macedonia",
    "NOR": "Norway",
    "OMN": "Oman",
    "PAK": "Pakistan",
    "PLW": "Palau",
    "PAN": "Panama",
    "PNG": "Papua New Guinea",
    "PRY": "Paraguay",
    "PER": "Peru",
    "PHL": "Philippines",
    "POL": "Poland",
    "PRT": "Portugal",
    "QAT": "Qatar",
    "ROU": "Romania",
    "RUS": "Russia",
    "RWA": "Rwanda",
    "KNA": "Saint Kitts and Nevis",
    "LCA": "Saint Lucia",
    "VCT": "Saint Vincent and the Grenadines",
    "WSM": "Samoa",
    "SMR": "San Marino",
    "STP": "São Tomé and Príncipe",
    "SAU": "Saudi Arabia",
    "SEN": "Senegal",
    "SRB": "Serbia",
    "SYC": "Seychelles",
    "SLE": "Sierra Leone",
    "SGP": "Singapore",
    "SVK": "Slovakia",
    "SVN": "Slovenia",
    "SLB": "Solomon Islands",
    "SOM": "Somalia",
    "ZAF": "South Africa",
    "KOR": "South Korea",
    "SSD": "South Sudan",
    "ESP": "Spain",
    "LKA": "Sri Lanka",
    "SDN": "Sudan",
    "SUR": "Suriname",
    "SWE": "Sweden",
    "CHE": "Switzerland",
    "SYR": "Syria",
    "TWN": "Taiwan",
    "TJK": "Tajikistan",
    "TZA": "Tanzania",
    "THA": "Thailand",
    "TLS": "Timor-Leste",
    "TGO": "Togo",
    "TON": "Tonga",
    "TTO": "Trinidad and Tobago",
    "TUN": "Tunisia",
    "TUR": "Türkiye",
    "TKM": "Turkmenistan",
    "TUV": "Tuvalu",
    "UGA": "Uganda",
    "UKR": "Ukraine",
    "ARE": "United Arab Emirates",
    "GBR": "United Kingdom",
    "USA": "United States",
    "URY": "Uruguay",
    "UZB": "Uzbekistan",
    "VUT": "Vanuatu",
    "VAT": "Vatican City",
    "VEN": "Venezuela",
    "VNM": "Vietnam",
    "YEM": "Yemen",
    "ZMB": "Zambia",
    "ZWE": "Zimbabwe"
}

function convertToName(code) {
  return countryCodesToNames[code]
}
